# Generated by Django 2.2.12 on 2020-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_city_to_50_chars'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de Ciudad', max_length=100, verbose_name='Nombre Ciudad')),
                ('lat', models.FloatField(help_text='Coordenada Y', verbose_name='Latitud')),
                ('lngt', models.FloatField(help_text='Coordenada X', verbose_name='Longitud')),
            ],
        ),
        migrations.CreateModel(
            name='provincias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de Provincia', max_length=100, verbose_name='Nombre Provicia')),
                ('lat', models.FloatField(help_text='Coordenada Y', verbose_name='Latitud')),
                ('lngt', models.FloatField(help_text='Coordenada X', verbose_name='Longitud')),
            ],
        ),
    ]
